# Generated by Django 3.0 on 2020-01-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200125_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='previous_post',
        ),
        migrations.AddField(
            model_name='post',
            name='previous_post',
            field=models.ManyToManyField(blank=True, null=True, related_name='_post_previous_post_+', to='posts.Post'),
        ),
    ]
